# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporter_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_panel = QtWidgets.QWidget(self.centralwidget)
        self.left_panel.setGeometry(QtCore.QRect(-1, 0, 211, 181))
        self.left_panel.setStyleSheet("border:1px solid #566D7E;\n"
"background-color: rgb(255, 255, 255);")
        self.left_panel.setObjectName("left_panel")
        self.label = QtWidgets.QLabel(self.left_panel)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../ASSETS/LOGO.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.panel_tabs_holder = QtWidgets.QTabWidget(self.centralwidget)
        self.panel_tabs_holder.setGeometry(QtCore.QRect(206, 0, 801, 601))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.panel_tabs_holder.setFont(font)
        self.panel_tabs_holder.setTabPosition(QtWidgets.QTabWidget.South)
        self.panel_tabs_holder.setObjectName("panel_tabs_holder")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.finance_widget = QtWidgets.QWidget(self.tab)
        self.finance_widget.setGeometry(QtCore.QRect(-1, -10, 791, 591))
        self.finance_widget.setStyleSheet("QWidget#finance_widget{\n"
"    background-color: rgb(149, 185, 199);\n"
"}")
        self.finance_widget.setObjectName("finance_widget")
        self.label_10 = QtWidgets.QLabel(self.finance_widget)
        self.label_10.setGeometry(QtCore.QRect(50, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.employee_details = QtWidgets.QWidget(self.finance_widget)
        self.employee_details.setGeometry(QtCore.QRect(30, 70, 741, 501))
        self.employee_details.setStyleSheet("QWidget#employee_details{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.employee_details.setObjectName("employee_details")
        self.label_11 = QtWidgets.QLabel(self.employee_details)
        self.label_11.setGeometry(QtCore.QRect(40, 270, 281, 31))
        self.label_11.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.employee_details)
        self.label_13.setGeometry(QtCore.QRect(100, 10, 161, 21))
        self.label_13.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.line_3 = QtWidgets.QFrame(self.employee_details)
        self.line_3.setGeometry(QtCore.QRect(380, 0, 20, 451))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.employee_preview_finance = QtWidgets.QListWidget(self.employee_details)
        self.employee_preview_finance.setGeometry(QtCore.QRect(30, 50, 331, 191))
        self.employee_preview_finance.setStyleSheet("font: 12pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.employee_preview_finance.setObjectName("employee_preview_finance")
        self.label_14 = QtWidgets.QLabel(self.employee_details)
        self.label_14.setGeometry(QtCore.QRect(60, 470, 651, 20))
        self.label_14.setStyleSheet("font: 12pt \"Courier\";")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.basic_pay_earned = QtWidgets.QSpinBox(self.employee_details)
        self.basic_pay_earned.setGeometry(QtCore.QRect(60, 310, 231, 51))
        self.basic_pay_earned.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.basic_pay_earned.setMaximum(999999999)
        self.basic_pay_earned.setObjectName("basic_pay_earned")
        self.save_basic_pay = QtWidgets.QPushButton(self.employee_details)
        self.save_basic_pay.setGeometry(QtCore.QRect(300, 310, 51, 51))
        self.save_basic_pay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_basic_pay.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        self.save_basic_pay.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/save_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_basic_pay.setIcon(icon)
        self.save_basic_pay.setIconSize(QtCore.QSize(32, 32))
        self.save_basic_pay.setObjectName("save_basic_pay")
        self.label_12 = QtWidgets.QLabel(self.employee_details)
        self.label_12.setGeometry(QtCore.QRect(410, 20, 151, 31))
        self.label_12.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.days_worked_selector = QtWidgets.QSpinBox(self.employee_details)
        self.days_worked_selector.setGeometry(QtCore.QRect(420, 60, 281, 41))
        self.days_worked_selector.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.days_worked_selector.setMaximum(999999999)
        self.days_worked_selector.setObjectName("days_worked_selector")
        self.label_16 = QtWidgets.QLabel(self.employee_details)
        self.label_16.setGeometry(QtCore.QRect(420, 120, 71, 31))
        self.label_16.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.employee_total_amount = QtWidgets.QLabel(self.employee_details)
        self.employee_total_amount.setGeometry(QtCore.QRect(440, 310, 281, 31))
        self.employee_total_amount.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.employee_total_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.employee_total_amount.setObjectName("employee_total_amount")
        self.line = QtWidgets.QFrame(self.employee_details)
        self.line.setGeometry(QtCore.QRect(0, 260, 391, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(self.employee_details)
        self.line_4.setGeometry(QtCore.QRect(0, 450, 741, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_18 = QtWidgets.QLabel(self.employee_details)
        self.label_18.setGeometry(QtCore.QRect(450, 260, 241, 31))
        self.label_18.setStyleSheet("font: 75 15pt \"Courier\";\n"
"background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.employee_details)
        self.label_19.setGeometry(QtCore.QRect(430, 180, 81, 31))
        self.label_19.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.employee_details)
        self.label_20.setGeometry(QtCore.QRect(20, 400, 91, 31))
        self.label_20.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.paid_no_paid_statistics = QtWidgets.QLabel(self.employee_details)
        self.paid_no_paid_statistics.setGeometry(QtCore.QRect(110, 400, 241, 31))
        self.paid_no_paid_statistics.setStyleSheet("font: 75 15pt \"Courier\";\n"
"background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);")
        self.paid_no_paid_statistics.setAlignment(QtCore.Qt.AlignCenter)
        self.paid_no_paid_statistics.setObjectName("paid_no_paid_statistics")
        self.line_5 = QtWidgets.QFrame(self.employee_details)
        self.line_5.setGeometry(QtCore.QRect(0, 370, 391, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.payment_status_show = QtWidgets.QLabel(self.employee_details)
        self.payment_status_show.setGeometry(QtCore.QRect(530, 180, 191, 31))
        self.payment_status_show.setStyleSheet("font: 75 15pt \"Courier\";\n"
"background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);")
        self.payment_status_show.setAlignment(QtCore.Qt.AlignCenter)
        self.payment_status_show.setObjectName("payment_status_show")
        self.employee_role_display = QtWidgets.QLabel(self.employee_details)
        self.employee_role_display.setGeometry(QtCore.QRect(510, 120, 211, 31))
        self.employee_role_display.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.employee_role_display.setAlignment(QtCore.Qt.AlignCenter)
        self.employee_role_display.setObjectName("employee_role_display")
        self.pay_employee_button = QtWidgets.QPushButton(self.employee_details)
        self.pay_employee_button.setGeometry(QtCore.QRect(460, 380, 241, 51))
        self.pay_employee_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pay_employee_button.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/pay_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pay_employee_button.setIcon(icon1)
        self.pay_employee_button.setIconSize(QtCore.QSize(32, 32))
        self.pay_employee_button.setObjectName("pay_employee_button")
        self.delete_cash_out = QtWidgets.QPushButton(self.employee_details)
        self.delete_cash_out.setGeometry(QtCore.QRect(460, 380, 241, 51))
        self.delete_cash_out.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_cash_out.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../assets/wipe_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_cash_out.setIcon(icon2)
        self.delete_cash_out.setIconSize(QtCore.QSize(32, 32))
        self.delete_cash_out.setObjectName("delete_cash_out")
        self.label_15 = QtWidgets.QLabel(self.finance_widget)
        self.label_15.setGeometry(QtCore.QRect(340, 20, 81, 31))
        self.label_15.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.current_month_display = QtWidgets.QComboBox(self.finance_widget)
        self.current_month_display.setGeometry(QtCore.QRect(420, 20, 291, 31))
        self.current_month_display.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.current_month_display.setObjectName("current_month_display")
        self.panel_tabs_holder.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.register_widget = QtWidgets.QWidget(self.tab_2)
        self.register_widget.setGeometry(QtCore.QRect(-1, -1, 801, 591))
        self.register_widget.setStyleSheet("QWidget#register_widget{\n"
"    background-color: rgb(149, 185, 199);\n"
"}")
        self.register_widget.setObjectName("register_widget")
        self.register_panel = QtWidgets.QWidget(self.register_widget)
        self.register_panel.setGeometry(QtCore.QRect(30, 60, 741, 271))
        self.register_panel.setStyleSheet("QWidget#register_panel{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.register_panel.setObjectName("register_panel")
        self.employee_name_input = QtWidgets.QLineEdit(self.register_panel)
        self.employee_name_input.setGeometry(QtCore.QRect(80, 30, 361, 31))
        self.employee_name_input.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.employee_name_input.setObjectName("employee_name_input")
        self.label_3 = QtWidgets.QLabel(self.register_panel)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_3.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.register_panel)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 61, 31))
        self.label_4.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.save_employee_button = QtWidgets.QPushButton(self.register_panel)
        self.save_employee_button.setGeometry(QtCore.QRect(80, 150, 361, 41))
        self.save_employee_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_employee_button.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:4px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../assets/users_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_employee_button.setIcon(icon3)
        self.save_employee_button.setIconSize(QtCore.QSize(32, 32))
        self.save_employee_button.setObjectName("save_employee_button")
        self.employee_role_input = QtWidgets.QComboBox(self.register_panel)
        self.employee_role_input.setGeometry(QtCore.QRect(80, 90, 361, 31))
        self.employee_role_input.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.employee_role_input.setObjectName("employee_role_input")
        self.label_6 = QtWidgets.QLabel(self.register_panel)
        self.label_6.setGeometry(QtCore.QRect(510, 10, 161, 21))
        self.label_6.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.delete_employee_trigger = QtWidgets.QPushButton(self.register_panel)
        self.delete_employee_trigger.setGeometry(QtCore.QRect(480, 200, 241, 41))
        self.delete_employee_trigger.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_employee_trigger.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:4px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        self.delete_employee_trigger.setIcon(icon2)
        self.delete_employee_trigger.setIconSize(QtCore.QSize(32, 32))
        self.delete_employee_trigger.setObjectName("delete_employee_trigger")
        self.line_2 = QtWidgets.QFrame(self.register_panel)
        self.line_2.setGeometry(QtCore.QRect(453, 0, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.employees_list_register = QtWidgets.QListWidget(self.register_panel)
        self.employees_list_register.setGeometry(QtCore.QRect(480, 50, 241, 131))
        self.employees_list_register.setStyleSheet("font: 12pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.employees_list_register.setObjectName("employees_list_register")
        self.register_error_label = QtWidgets.QLabel(self.register_panel)
        self.register_error_label.setGeometry(QtCore.QRect(30, 230, 411, 20))
        self.register_error_label.setStyleSheet("font: 12pt \"Courier\";")
        self.register_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.register_error_label.setObjectName("register_error_label")
        self.label_2 = QtWidgets.QLabel(self.register_widget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.register_widget)
        self.label_5.setGeometry(QtCore.QRect(50, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.roles_panel = QtWidgets.QWidget(self.register_widget)
        self.roles_panel.setGeometry(QtCore.QRect(40, 400, 651, 151))
        self.roles_panel.setStyleSheet("QWidget#roles_panel{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.roles_panel.setObjectName("roles_panel")
        self.role_register_input = QtWidgets.QLineEdit(self.roles_panel)
        self.role_register_input.setGeometry(QtCore.QRect(190, 20, 351, 31))
        self.role_register_input.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.role_register_input.setObjectName("role_register_input")
        self.label_7 = QtWidgets.QLabel(self.roles_panel)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 171, 31))
        self.label_7.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.save_new_role = QtWidgets.QPushButton(self.roles_panel)
        self.save_new_role.setGeometry(QtCore.QRect(560, 10, 51, 51))
        self.save_new_role.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_new_role.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        self.save_new_role.setText("")
        self.save_new_role.setIcon(icon)
        self.save_new_role.setIconSize(QtCore.QSize(32, 32))
        self.save_new_role.setObjectName("save_new_role")
        self.label_9 = QtWidgets.QLabel(self.roles_panel)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 161, 31))
        self.label_9.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.available_roles_list = QtWidgets.QComboBox(self.roles_panel)
        self.available_roles_list.setGeometry(QtCore.QRect(190, 100, 351, 31))
        self.available_roles_list.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.available_roles_list.setObjectName("available_roles_list")
        self.delete_present_role = QtWidgets.QPushButton(self.roles_panel)
        self.delete_present_role.setGeometry(QtCore.QRect(560, 90, 51, 51))
        self.delete_present_role.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_present_role.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        self.delete_present_role.setText("")
        self.delete_present_role.setIcon(icon2)
        self.delete_present_role.setIconSize(QtCore.QSize(32, 32))
        self.delete_present_role.setObjectName("delete_present_role")
        self.line_8 = QtWidgets.QFrame(self.roles_panel)
        self.line_8.setGeometry(QtCore.QRect(0, 70, 651, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.role_register_input.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.available_roles_list.raise_()
        self.delete_present_role.raise_()
        self.save_new_role.raise_()
        self.line_8.raise_()
        self.panel_tabs_holder.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.reports_widget = QtWidgets.QWidget(self.tab_3)
        self.reports_widget.setGeometry(QtCore.QRect(0, -10, 801, 591))
        self.reports_widget.setStyleSheet("QWidget#reports_widget{\n"
"    background-color: rgb(149, 185, 199);\n"
"}")
        self.reports_widget.setObjectName("reports_widget")
        self.label_22 = QtWidgets.QLabel(self.reports_widget)
        self.label_22.setGeometry(QtCore.QRect(70, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(86, 109, 126);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.report_generator_panel = QtWidgets.QWidget(self.reports_widget)
        self.report_generator_panel.setGeometry(QtCore.QRect(30, 90, 741, 471))
        self.report_generator_panel.setStyleSheet("QWidget#report_generator_panel{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.report_generator_panel.setObjectName("report_generator_panel")
        self.label_24 = QtWidgets.QLabel(self.report_generator_panel)
        self.label_24.setGeometry(QtCore.QRect(50, 20, 61, 31))
        self.label_24.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.report_year_list = QtWidgets.QComboBox(self.report_generator_panel)
        self.report_year_list.setGeometry(QtCore.QRect(120, 20, 181, 31))
        self.report_year_list.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.report_year_list.setObjectName("report_year_list")
        self.report_error_label = QtWidgets.QLabel(self.report_generator_panel)
        self.report_error_label.setGeometry(QtCore.QRect(150, 429, 411, 31))
        self.report_error_label.setStyleSheet("font: 12pt \"Courier\";")
        self.report_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.report_error_label.setObjectName("report_error_label")
        self.label_27 = QtWidgets.QLabel(self.report_generator_panel)
        self.label_27.setGeometry(QtCore.QRect(340, 20, 81, 31))
        self.label_27.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.report_month_list = QtWidgets.QComboBox(self.report_generator_panel)
        self.report_month_list.setGeometry(QtCore.QRect(430, 20, 291, 31))
        self.report_month_list.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color:rgb(86, 109, 126);")
        self.report_month_list.setObjectName("report_month_list")
        self.line_6 = QtWidgets.QFrame(self.report_generator_panel)
        self.line_6.setGeometry(QtCore.QRect(0, 60, 741, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.report_generator_panel)
        self.line_7.setGeometry(QtCore.QRect(0, 420, 741, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.report_details = QtWidgets.QTextEdit(self.report_generator_panel)
        self.report_details.setGeometry(QtCore.QRect(20, 110, 511, 301))
        self.report_details.setStyleSheet("font: 12pt \"Courier\";")
        self.report_details.setObjectName("report_details")
        self.label_23 = QtWidgets.QLabel(self.report_generator_panel)
        self.label_23.setGeometry(QtCore.QRect(20, 80, 221, 21))
        self.label_23.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.generate_report_trigger = QtWidgets.QPushButton(self.report_generator_panel)
        self.generate_report_trigger.setGeometry(QtCore.QRect(550, 210, 171, 51))
        self.generate_report_trigger.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate_report_trigger.setStyleSheet("font:12pt \"Courier\";\n"
"QPushButton{\n"
"background-color: #566D7E;\n"
"border-radius:25px;\n"
"color: rgb(255, 255, 255);\n"
"font:12pt \"Courier\";\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../assets/export_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.generate_report_trigger.setIcon(icon4)
        self.generate_report_trigger.setIconSize(QtCore.QSize(32, 32))
        self.generate_report_trigger.setObjectName("generate_report_trigger")
        self.panel_tabs_holder.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.about_widget = QtWidgets.QWidget(self.tab_4)
        self.about_widget.setGeometry(QtCore.QRect(0, -10, 801, 591))
        self.about_widget.setStyleSheet("QWidget#about_widget{\n"
"    background-color: rgb(149, 185, 199);\n"
"}")
        self.about_widget.setObjectName("about_widget")
        self.about_details = QtWidgets.QWidget(self.about_widget)
        self.about_details.setGeometry(QtCore.QRect(30, 60, 741, 491))
        self.about_details.setStyleSheet("QWidget#about_details{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.about_details.setObjectName("about_details")
        self.register_error_label_2 = QtWidgets.QLabel(self.about_details)
        self.register_error_label_2.setGeometry(QtCore.QRect(50, 90, 641, 311))
        self.register_error_label_2.setStyleSheet("font: 75 15pt \"Courier\";\n"
"color: rgb(86, 109, 126);")
        self.register_error_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.register_error_label_2.setObjectName("register_error_label_2")
        self.panel_tabs_holder.addTab(self.tab_4, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, 179, 211, 421))
        self.widget.setStyleSheet("background-color: rgb(86, 109, 126);")
        self.widget.setObjectName("widget")
        self.visit_finance = QtWidgets.QPushButton(self.widget)
        self.visit_finance.setGeometry(QtCore.QRect(0, 120, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.visit_finance.setFont(font)
        self.visit_finance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visit_finance.setStyleSheet("QPushButton{\n"
"background-color: #566D7E;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../assets/finance_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.visit_finance.setIcon(icon5)
        self.visit_finance.setIconSize(QtCore.QSize(32, 32))
        self.visit_finance.setObjectName("visit_finance")
        self.visit_register = QtWidgets.QPushButton(self.widget)
        self.visit_register.setGeometry(QtCore.QRect(0, 210, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.visit_register.setFont(font)
        self.visit_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visit_register.setStyleSheet("QPushButton{\n"
"background-color: #566D7E;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        self.visit_register.setIcon(icon3)
        self.visit_register.setIconSize(QtCore.QSize(32, 32))
        self.visit_register.setObjectName("visit_register")
        self.visit_history = QtWidgets.QPushButton(self.widget)
        self.visit_history.setGeometry(QtCore.QRect(0, 310, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(12)
        self.visit_history.setFont(font)
        self.visit_history.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visit_history.setStyleSheet("QPushButton{\n"
"background-color: #566D7E;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #123456;\n"
"    font:75 15pt \"Courier\";\n"
"\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../assets/history_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.visit_history.setIcon(icon6)
        self.visit_history.setIconSize(QtCore.QSize(32, 32))
        self.visit_history.setObjectName("visit_history")
        self.date_display_label = QtWidgets.QLabel(self.widget)
        self.date_display_label.setGeometry(QtCore.QRect(10, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.date_display_label.setFont(font)
        self.date_display_label.setStyleSheet("background-color: rgb(38, 38, 97);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 15pt \"Courier\";\n"
"border-radius:20px;")
        self.date_display_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_display_label.setObjectName("date_display_label")
        self.line_9 = QtWidgets.QFrame(self.widget)
        self.line_9.setGeometry(QtCore.QRect(-30, 90, 241, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.widget)
        self.line_10.setGeometry(QtCore.QRect(-10, 190, 221, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.widget)
        self.line_11.setGeometry(QtCore.QRect(-10, 280, 221, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.widget)
        self.line_12.setGeometry(QtCore.QRect(-10, 380, 221, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.panel_tabs_holder.raise_()
        self.widget.raise_()
        self.left_panel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.panel_tabs_holder.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Skills Reporter \u00A9 2023"))
        self.label_10.setText(_translate("MainWindow", "EMPLOYEE  DETAIL"))
        self.label_11.setText(_translate("MainWindow", "BASIC AMOUNT PER DAY"))
        self.label_13.setText(_translate("MainWindow", "EMPLOYEES"))
        self.employee_preview_finance.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Select an employee to compute their pay</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "All rights reserved ssec"))
        self.basic_pay_earned.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Set the daily pay that is to be earned per day</span></p></body></html>"))
        self.save_basic_pay.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save Basic Pay</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "DAYS WORKED"))
        self.days_worked_selector.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Select the number of days worked</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "ROLE"))
        self.employee_total_amount.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">How much is paid for the days worked</p></body></html>"))
        self.employee_total_amount.setText(_translate("MainWindow", "0/="))
        self.label_18.setText(_translate("MainWindow", "TOTAL AMOUNT"))
        self.label_19.setText(_translate("MainWindow", "STATUS"))
        self.label_20.setText(_translate("MainWindow", "PAID"))
        self.paid_no_paid_statistics.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#566d7e;\">Shows ratio of those paid to those pending</span></p></body></html>"))
        self.paid_no_paid_statistics.setText(_translate("MainWindow", "0/0"))
        self.payment_status_show.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#566d7e;\">Green</span><span style=\" font-size:12pt; color:#566d7e;\"> - Was Paid</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#566d7e;\">Grey</span><span style=\" font-size:12pt; color:#566d7e;\"> - Not yet Paid</span></p></body></html>"))
        self.payment_status_show.setText(_translate("MainWindow", "PENDING"))
        self.employee_role_display.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">What position the employee has at the organization</span></p></body></html>"))
        self.employee_role_display.setText(_translate("MainWindow", "---"))
        self.pay_employee_button.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mark the employee paid</p></body></html>"))
        self.pay_employee_button.setText(_translate("MainWindow", "CASH OUT"))
        self.delete_cash_out.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Unmark Employee as paid</p></body></html>"))
        self.delete_cash_out.setText(_translate("MainWindow", "REVERSE"))
        self.label_15.setText(_translate("MainWindow", "MONTH"))
        self.current_month_display.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Present Month based on computer calendar</span></p></body></html>"))
        self.panel_tabs_holder.setTabText(self.panel_tabs_holder.indexOf(self.tab), _translate("MainWindow", "Finance"))
        self.employee_name_input.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Names of the employee</p><p align=\"center\"><span style=\" font-weight:600;\">Note:</span> An employee cant be registered twice</p></body></html>"))
        self.employee_name_input.setPlaceholderText(_translate("MainWindow", "i.e. John Doe"))
        self.label_3.setText(_translate("MainWindow", "NAME"))
        self.label_4.setText(_translate("MainWindow", "ROLE"))
        self.save_employee_button.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Save the employee details</p></body></html>"))
        self.save_employee_button.setText(_translate("MainWindow", "SAVE"))
        self.employee_role_input.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Select a role that employee holds</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "PRESENT"))
        self.delete_employee_trigger.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Delete selected employee</p></body></html>"))
        self.delete_employee_trigger.setText(_translate("MainWindow", "DELETE"))
        self.employees_list_register.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Select an employee to delete</p></body></html>"))
        self.register_error_label.setText(_translate("MainWindow", "All rights reserved ssec"))
        self.label_2.setText(_translate("MainWindow", "EMPLOYEE  REGISTER"))
        self.label_5.setText(_translate("MainWindow", "ROLES ENTRY"))
        self.role_register_input.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Create a new category</p><p align=\"center\"><span style=\" font-weight:600;\">Note:</span> A category cant be registered twice</p></body></html>"))
        self.role_register_input.setPlaceholderText(_translate("MainWindow", "i.e. Chef"))
        self.label_7.setText(_translate("MainWindow", "ROLE CATEGORY"))
        self.save_new_role.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Save New Category</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "AVAILABLE"))
        self.available_roles_list.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Select a category to delete</span></p></body></html>"))
        self.delete_present_role.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Delete selected role</p><p align=\"center\"><span style=\" font-weight:600;\">Note:</span> Employees with that role wont be deleted</p></body></html>"))
        self.panel_tabs_holder.setTabText(self.panel_tabs_holder.indexOf(self.tab_2), _translate("MainWindow", "Register"))
        self.label_22.setText(_translate("MainWindow", "MONTHLY PAY REPORT"))
        self.label_24.setText(_translate("MainWindow", "YEAR"))
        self.report_year_list.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Select Year of Reporting</span></p><p align=\"center\"><span style=\" font-size:11pt;\">Default is current year</span></p></body></html>"))
        self.report_error_label.setText(_translate("MainWindow", "All rights reserved ssec"))
        self.label_27.setText(_translate("MainWindow", "MONTH"))
        self.report_month_list.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">select any month </span></p></body></html>"))
        self.report_details.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Report Details appear here</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "PAYMENT DETAILS"))
        self.generate_report_trigger.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Generate Report</p><p align=\"center\"><span style=\" font-weight:600;\">Note:</span> Report will be saved in a folder at the desktop</p></body></html>"))
        self.generate_report_trigger.setText(_translate("MainWindow", "EXPORT"))
        self.panel_tabs_holder.setTabText(self.panel_tabs_holder.indexOf(self.tab_3), _translate("MainWindow", "Reports"))
        self.register_error_label_2.setText(_translate("MainWindow", "This application is a minimal finance\n"
" records management system, handy in managing reports\n"
", payments and related data\n"
"\n"
"Developer: Grace Peter Mutiibwa"))
        self.panel_tabs_holder.setTabText(self.panel_tabs_holder.indexOf(self.tab_4), _translate("MainWindow", "About"))
        self.visit_finance.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\" style=\"font-family:\'Courier\';font-size:12pt; \">Goto Finance Panel</p></body></html>"))
        self.visit_finance.setText(_translate("MainWindow", "Finance"))
        self.visit_register.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\" style=\"font-family:\'Courier\';font-size:12pt; \">Goto Register Panel</p></body></html>"))
        self.visit_register.setText(_translate("MainWindow", "Register"))
        self.visit_history.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\" style=\"font-family:\'Courier\';font-size:12pt; \">Goto Reports Panel</p></body></html>"))
        self.visit_history.setText(_translate("MainWindow", "Reports"))
        self.date_display_label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Today\'s Date</p></body></html>"))
        self.date_display_label.setText(_translate("MainWindow", "---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
